# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER gpx

# 挂载目录
VOLUME /home/gpx
# 创建目录
RUN mkdir -p /home/gpx
# 指定路径
WORKDIR /home/gpx
# 复制jar文件到路径
COPY ./jar/gpx-modules-job.jar /home/gpx/gpx-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","gpx-modules-job.jar"]