# 基础镜像
FROM nginx
# author
MAINTAINER gpx

# 挂载目录
VOLUME /home/gpx/projects/gpx-ui
# 创建目录
RUN mkdir -p /home/gpx/projects/gpx-ui
# 指定路径
WORKDIR /home/gpx/projects/gpx-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/gpx/projects/gpx-ui
