# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER gpx

# 挂载目录
VOLUME /home/gpx
# 创建目录
RUN mkdir -p /home/gpx
# 指定路径
WORKDIR /home/gpx
# 复制jar文件到路径
COPY ./jar/gpx-gateway.jar /home/gpx/gpx-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","gpx-gateway.jar"]